# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147RAwtULBljxCjPbQrsmogepMVa7vLYW
"""

# STEP 1: Install YOLOv8 and OpenCV
!pip install ultralytics opencv-python

# STEP 2: Import necessary libraries
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
import numpy as np

# STEP 3: Load YOLOv8 model (you can use yolov8n, yolov8s, etc.)
model = YOLO('yolov8n.pt')  # lightweight and fast

# STEP 4: Upload a video or use webcam (here we’ll process a sample image to simulate)
from google.colab import files
uploaded = files.upload() # Modified to open file picker

# STEP 5: Read uploaded image/video file
import os
file_name = list(uploaded.keys())[0]

# STEP 6: Run object detection
results = model(file_name)

# STEP 7: Display result (for image only — video requires looped frame processing)
results[0].show()  # Will open detected image in output

